modLoader="javafml" #mandatory
loaderVersion="[36,)" 
# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="GPL 3.0"

[[mods]]
modId="lotrcompanions"
version="${version}"
displayName="LOTR: Companions"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional

# A file name (in the root of the mod JAR) containing a logo for display
logoFile="lotrcompanions_logo.png" #optional

credits='''
Developer: RichardPlaysMC
Additional Development: Maximuslotro
Some code comes from the Human Companions mod
Thanks to Mevans for developing the LOTR mod!
'''

authors="RichardPlaysMC, MaximusLotro"

# The description text for the mod (multi line!) (#mandatory)
description='''
This mod is inspired by the Human Companions mod to reimplement hireable units into LOTR: Renewed
'''

[[dependencies.lotrcompanions]] #optional
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.lotrcompanions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.lotrcompanions]]
    modId="lotr"
    mandatory=true
    versionRange="Renewed-5.5"
    ordering="BEFORE"
    side="BOTH"